/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.xtext.ui.tests;

import com.google.inject.Injector;
import es.unican.ildm.practica3.xtext.factory.ui.internal.FactoryActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FactoryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FactoryActivator.getInstance().getInjector("es.unican.ildm.practica3.xtext.Factory");
	}

}
