/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory.impl;

import es.unican.ildm.practica3.factory.FactoryPackage;
import es.unican.ildm.practica3.factory.Machine;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Machine</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.impl.MachineImpl#getManufacturer <em>Manufacturer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MachineImpl extends ElementImpl implements Machine
{
  /**
   * The default value of the '{@link #getManufacturer() <em>Manufacturer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManufacturer()
   * @generated
   * @ordered
   */
  protected static final String MANUFACTURER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getManufacturer() <em>Manufacturer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManufacturer()
   * @generated
   * @ordered
   */
  protected String manufacturer = MANUFACTURER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MachineImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FactoryPackage.Literals.MACHINE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getManufacturer()
  {
    return manufacturer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setManufacturer(String newManufacturer)
  {
    String oldManufacturer = manufacturer;
    manufacturer = newManufacturer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FactoryPackage.MACHINE__MANUFACTURER, oldManufacturer, manufacturer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FactoryPackage.MACHINE__MANUFACTURER:
        return getManufacturer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FactoryPackage.MACHINE__MANUFACTURER:
        setManufacturer((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FactoryPackage.MACHINE__MANUFACTURER:
        setManufacturer(MANUFACTURER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FactoryPackage.MACHINE__MANUFACTURER:
        return MANUFACTURER_EDEFAULT == null ? manufacturer != null : !MANUFACTURER_EDEFAULT.equals(manufacturer);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (manufacturer: ");
    result.append(manufacturer);
    result.append(')');
    return result.toString();
  }

} //MachineImpl
