/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFactoryValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(es.unican.ildm.practica3.factory.FactoryPackage.eINSTANCE);
		return result;
	}
}
