/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Factory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.Factory#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see es.unican.ildm.practica3.factory.FactoryPackage#getFactory()
 * @model
 * @generated
 */
public interface Factory extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link es.unican.ildm.practica3.factory.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getFactory_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Factory
