/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see es.unican.ildm.practica3.factory.FactoryFactory
 * @model kind="package"
 * @generated
 */
public interface FactoryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "factory";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unican.es/ildm/practica3/Factory";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "factory";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FactoryPackage eINSTANCE = es.unican.ildm.practica3.factory.impl.FactoryPackageImpl.init();

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.FactoryImpl <em>Factory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.FactoryImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getFactory()
   * @generated
   */
  int FACTORY = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTORY__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Factory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.ElementImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.ShiftImpl <em>Shift</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.ShiftImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getShift()
   * @generated
   */
  int SHIFT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT__DATE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Work</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT__WORK = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Shift</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.TaskImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getTask()
   * @generated
   */
  int TASK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DURATION = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__OPERATOR = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Machine</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__MACHINE = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.OperatorImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR__AREA = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link es.unican.ildm.practica3.factory.impl.MachineImpl <em>Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.unican.ildm.practica3.factory.impl.MachineImpl
   * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getMachine()
   * @generated
   */
  int MACHINE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Manufacturer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__MANUFACTURER = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Factory <em>Factory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factory</em>'.
   * @see es.unican.ildm.practica3.factory.Factory
   * @generated
   */
  EClass getFactory();

  /**
   * Returns the meta object for the containment reference list '{@link es.unican.ildm.practica3.factory.Factory#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see es.unican.ildm.practica3.factory.Factory#getElements()
   * @see #getFactory()
   * @generated
   */
  EReference getFactory_Elements();

  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see es.unican.ildm.practica3.factory.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link es.unican.ildm.practica3.factory.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see es.unican.ildm.practica3.factory.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Shift <em>Shift</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shift</em>'.
   * @see es.unican.ildm.practica3.factory.Shift
   * @generated
   */
  EClass getShift();

  /**
   * Returns the meta object for the attribute '{@link es.unican.ildm.practica3.factory.Shift#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see es.unican.ildm.practica3.factory.Shift#getDate()
   * @see #getShift()
   * @generated
   */
  EAttribute getShift_Date();

  /**
   * Returns the meta object for the reference list '{@link es.unican.ildm.practica3.factory.Shift#getWork <em>Work</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Work</em>'.
   * @see es.unican.ildm.practica3.factory.Shift#getWork()
   * @see #getShift()
   * @generated
   */
  EReference getShift_Work();

  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see es.unican.ildm.practica3.factory.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link es.unican.ildm.practica3.factory.Task#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see es.unican.ildm.practica3.factory.Task#getDuration()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Duration();

  /**
   * Returns the meta object for the reference '{@link es.unican.ildm.practica3.factory.Task#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Operator</em>'.
   * @see es.unican.ildm.practica3.factory.Task#getOperator()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Operator();

  /**
   * Returns the meta object for the reference '{@link es.unican.ildm.practica3.factory.Task#getMachine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Machine</em>'.
   * @see es.unican.ildm.practica3.factory.Task#getMachine()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Machine();

  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see es.unican.ildm.practica3.factory.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for the attribute '{@link es.unican.ildm.practica3.factory.Operator#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see es.unican.ildm.practica3.factory.Operator#getArea()
   * @see #getOperator()
   * @generated
   */
  EAttribute getOperator_Area();

  /**
   * Returns the meta object for class '{@link es.unican.ildm.practica3.factory.Machine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine</em>'.
   * @see es.unican.ildm.practica3.factory.Machine
   * @generated
   */
  EClass getMachine();

  /**
   * Returns the meta object for the attribute '{@link es.unican.ildm.practica3.factory.Machine#getManufacturer <em>Manufacturer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Manufacturer</em>'.
   * @see es.unican.ildm.practica3.factory.Machine#getManufacturer()
   * @see #getMachine()
   * @generated
   */
  EAttribute getMachine_Manufacturer();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FactoryFactory getFactoryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.FactoryImpl <em>Factory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.FactoryImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getFactory()
     * @generated
     */
    EClass FACTORY = eINSTANCE.getFactory();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTORY__ELEMENTS = eINSTANCE.getFactory_Elements();

    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.ElementImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.ShiftImpl <em>Shift</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.ShiftImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getShift()
     * @generated
     */
    EClass SHIFT = eINSTANCE.getShift();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHIFT__DATE = eINSTANCE.getShift_Date();

    /**
     * The meta object literal for the '<em><b>Work</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHIFT__WORK = eINSTANCE.getShift_Work();

    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.TaskImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DURATION = eINSTANCE.getTask_Duration();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__OPERATOR = eINSTANCE.getTask_Operator();

    /**
     * The meta object literal for the '<em><b>Machine</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__MACHINE = eINSTANCE.getTask_Machine();

    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.OperatorImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATOR__AREA = eINSTANCE.getOperator_Area();

    /**
     * The meta object literal for the '{@link es.unican.ildm.practica3.factory.impl.MachineImpl <em>Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.unican.ildm.practica3.factory.impl.MachineImpl
     * @see es.unican.ildm.practica3.factory.impl.FactoryPackageImpl#getMachine()
     * @generated
     */
    EClass MACHINE = eINSTANCE.getMachine();

    /**
     * The meta object literal for the '<em><b>Manufacturer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MACHINE__MANUFACTURER = eINSTANCE.getMachine_Manufacturer();

  }

} //FactoryPackage
