/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Machine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.Machine#getManufacturer <em>Manufacturer</em>}</li>
 * </ul>
 *
 * @see es.unican.ildm.practica3.factory.FactoryPackage#getMachine()
 * @model
 * @generated
 */
public interface Machine extends Element
{
  /**
   * Returns the value of the '<em><b>Manufacturer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer</em>' attribute.
   * @see #setManufacturer(String)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getMachine_Manufacturer()
   * @model
   * @generated
   */
  String getManufacturer();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Machine#getManufacturer <em>Manufacturer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer</em>' attribute.
   * @see #getManufacturer()
   * @generated
   */
  void setManufacturer(String value);

} // Machine
