/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.Operator#getArea <em>Area</em>}</li>
 * </ul>
 *
 * @see es.unican.ildm.practica3.factory.FactoryPackage#getOperator()
 * @model
 * @generated
 */
public interface Operator extends Element
{
  /**
   * Returns the value of the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Area</em>' attribute.
   * @see #setArea(String)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getOperator_Area()
   * @model
   * @generated
   */
  String getArea();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Operator#getArea <em>Area</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Area</em>' attribute.
   * @see #getArea()
   * @generated
   */
  void setArea(String value);

} // Operator
