/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shift</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.Shift#getDate <em>Date</em>}</li>
 *   <li>{@link es.unican.ildm.practica3.factory.Shift#getWork <em>Work</em>}</li>
 * </ul>
 *
 * @see es.unican.ildm.practica3.factory.FactoryPackage#getShift()
 * @model
 * @generated
 */
public interface Shift extends Element
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getShift_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Shift#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Work</b></em>' reference list.
   * The list contents are of type {@link es.unican.ildm.practica3.factory.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work</em>' reference list.
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getShift_Work()
   * @model
   * @generated
   */
  EList<Task> getWork();

} // Shift
