/**
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.factory;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.unican.ildm.practica3.factory.Task#getDuration <em>Duration</em>}</li>
 *   <li>{@link es.unican.ildm.practica3.factory.Task#getOperator <em>Operator</em>}</li>
 *   <li>{@link es.unican.ildm.practica3.factory.Task#getMachine <em>Machine</em>}</li>
 * </ul>
 *
 * @see es.unican.ildm.practica3.factory.FactoryPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends Element
{
  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(Integer)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getTask_Duration()
   * @model
   * @generated
   */
  Integer getDuration();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Task#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Integer value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' reference.
   * @see #setOperator(Operator)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getTask_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Task#getOperator <em>Operator</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Machine</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Machine</em>' reference.
   * @see #setMachine(Machine)
   * @see es.unican.ildm.practica3.factory.FactoryPackage#getTask_Machine()
   * @model
   * @generated
   */
  Machine getMachine();

  /**
   * Sets the value of the '{@link es.unican.ildm.practica3.factory.Task#getMachine <em>Machine</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Machine</em>' reference.
   * @see #getMachine()
   * @generated
   */
  void setMachine(Machine value);

} // Task
