/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica4.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.unican.ildm.practica4.xtext.FactoryRuntimeModule;
import es.unican.ildm.practica4.xtext.FactoryStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FactoryIdeSetup extends FactoryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FactoryRuntimeModule(), new FactoryIdeModule()));
	}
	
}
