/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica4.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class FactoryIdeModule extends AbstractFactoryIdeModule {
}
