/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica3.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFactoryScopeProvider extends DelegatingScopeProvider {
}
