<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="candy_factory" nsURI="http://www.unican.es/ildm/candy_factory"
    nsPrefix="candy_factory">
  <eClassifiers xsi:type="ecore:EClass" name="Factory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//ConveyorBelt"
        eOpposite="#//ConveyorBelt/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//ConveyorBelt" eOpposite="#//ConveyorBelt/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConveyorBelt" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Machine"
        eOpposite="#//Machine/input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Machine"
        eOpposite="#//Machine/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Producer" abstract="true" eSuperTypes="#//Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assembler" eSuperTypes="#//Machine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wrapper" eSuperTypes="#//Machine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flattener" eSuperTypes="#//Machine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CandyProducer" eSuperTypes="#//Producer"/>
  <eClassifiers xsi:type="ecore:EClass" name="StickProducer" eSuperTypes="#//Producer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stick" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="CandyFlat" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="CandyBall" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lollipop" eSuperTypes="#//Component"/>
</ecore:EPackage>
