/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica4.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FactoryUiModule extends AbstractFactoryUiModule {

	public FactoryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
