/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica4.xtext.parser.antlr;

import com.google.inject.Inject;
import es.unican.ildm.practica4.xtext.parser.antlr.internal.InternalFactoryParser;
import es.unican.ildm.practica4.xtext.services.FactoryGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FactoryParser extends AbstractAntlrParser {

	@Inject
	private FactoryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFactoryParser createParser(XtextTokenStream stream) {
		return new InternalFactoryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Factory";
	}

	public FactoryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FactoryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
