/*
 * generated by Xtext 2.31.0
 */
package es.unican.ildm.practica4.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FactoryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/unican/ildm/practica4/xtext/parser/antlr/internal/InternalFactory.tokens");
	}
}
